/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XpHistoryRouteImport } from './routes/xp-history'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as TitlesRouteImport } from './routes/titles'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StarterRouteImport } from './routes/starter'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as QuestsIndexRouteImport } from './routes/quests.index'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as FounderIndexRouteImport } from './routes/founder.index'
import { Route as StudioMediaRouteImport } from './routes/studio.media'
import { Route as StudioAuditRouteImport } from './routes/studio.audit'
import { Route as SettingsSocialRouteImport } from './routes/settings.social'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as QuestsSlugRouteImport } from './routes/quests.$slug'
import { Route as PlayersUsernameRouteImport } from './routes/players.$username'
import { Route as FounderTitlesRouteImport } from './routes/founder.titles'
import { Route as FounderSocialRouteImport } from './routes/founder.social'
import { Route as FounderLiveopsRouteImport } from './routes/founder.liveops'
import { Route as FounderCollectionsRouteImport } from './routes/founder.collections'
import { Route as FounderAchievementsRouteImport } from './routes/founder.achievements'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as AchievementsSlugRouteImport } from './routes/achievements.$slug'
import { Route as StudioPlayersIndexRouteImport } from './routes/studio.players.index'
import { Route as FounderQuestsIndexRouteImport } from './routes/founder.quests.index'
import { Route as StudioPlayersUserIdRouteImport } from './routes/studio.players.$userId'
import { Route as QuestsSlugPlayRouteImport } from './routes/quests.$slug.play'
import { Route as PlayersUsernameCompareRouteImport } from './routes/players.$username.compare'
import { Route as FounderQuestsNewRouteImport } from './routes/founder.quests.new'
import { Route as FounderQuestsIdRouteImport } from './routes/founder.quests.$id'
import { Route as FounderCollectionsIdRouteImport } from './routes/founder.collections.$id'
import { Route as ApiPublicHooksLiveopsTickRouteImport } from './routes/api/public/hooks/liveops-tick'

const XpHistoryRoute = XpHistoryRouteImport.update({
  id: '/xp-history',
  path: '/xp-history',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const TitlesRoute = TitlesRouteImport.update({
  id: '/titles',
  path: '/titles',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StarterRoute = StarterRouteImport.update({
  id: '/starter',
  path: '/starter',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsIndexRoute = QuestsIndexRouteImport.update({
  id: '/quests/',
  path: '/quests/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderIndexRoute = FounderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FounderRoute,
} as any)
const StudioMediaRoute = StudioMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAuditRoute = StudioAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => StudioRoute,
} as any)
const SettingsSocialRoute = SettingsSocialRouteImport.update({
  id: '/settings/social',
  path: '/settings/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsSlugRoute = QuestsSlugRouteImport.update({
  id: '/quests/$slug',
  path: '/quests/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersUsernameRoute = PlayersUsernameRouteImport.update({
  id: '/players/$username',
  path: '/players/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderTitlesRoute = FounderTitlesRouteImport.update({
  id: '/titles',
  path: '/titles',
  getParentRoute: () => FounderRoute,
} as any)
const FounderSocialRoute = FounderSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => FounderRoute,
} as any)
const FounderLiveopsRoute = FounderLiveopsRouteImport.update({
  id: '/liveops',
  path: '/liveops',
  getParentRoute: () => FounderRoute,
} as any)
const FounderCollectionsRoute = FounderCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => FounderRoute,
} as any)
const FounderAchievementsRoute = FounderAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => FounderRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionsRoute,
} as any)
const AchievementsSlugRoute = AchievementsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AchievementsRoute,
} as any)
const StudioPlayersIndexRoute = StudioPlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => StudioRoute,
} as any)
const FounderQuestsIndexRoute = FounderQuestsIndexRouteImport.update({
  id: '/quests/',
  path: '/quests/',
  getParentRoute: () => FounderRoute,
} as any)
const StudioPlayersUserIdRoute = StudioPlayersUserIdRouteImport.update({
  id: '/players/$userId',
  path: '/players/$userId',
  getParentRoute: () => StudioRoute,
} as any)
const QuestsSlugPlayRoute = QuestsSlugPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => QuestsSlugRoute,
} as any)
const PlayersUsernameCompareRoute = PlayersUsernameCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => PlayersUsernameRoute,
} as any)
const FounderQuestsNewRoute = FounderQuestsNewRouteImport.update({
  id: '/quests/new',
  path: '/quests/new',
  getParentRoute: () => FounderRoute,
} as any)
const FounderQuestsIdRoute = FounderQuestsIdRouteImport.update({
  id: '/quests/$id',
  path: '/quests/$id',
  getParentRoute: () => FounderRoute,
} as any)
const FounderCollectionsIdRoute = FounderCollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FounderCollectionsRoute,
} as any)
const ApiPublicHooksLiveopsTickRoute =
  ApiPublicHooksLiveopsTickRouteImport.update({
    id: '/api/public/hooks/liveops-tick',
    path: '/api/public/hooks/liveops-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRouteWithChildren
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/founder': typeof FounderRouteWithChildren
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/starter': typeof StarterRoute
  '/studio': typeof StudioRouteWithChildren
  '/titles': typeof TitlesRoute
  '/tutorial': typeof TutorialRoute
  '/welcome': typeof WelcomeRoute
  '/xp-history': typeof XpHistoryRoute
  '/achievements/$slug': typeof AchievementsSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/founder/achievements': typeof FounderAchievementsRoute
  '/founder/collections': typeof FounderCollectionsRouteWithChildren
  '/founder/liveops': typeof FounderLiveopsRoute
  '/founder/social': typeof FounderSocialRoute
  '/founder/titles': typeof FounderTitlesRoute
  '/players/$username': typeof PlayersUsernameRouteWithChildren
  '/quests/$slug': typeof QuestsSlugRouteWithChildren
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/social': typeof SettingsSocialRoute
  '/studio/audit': typeof StudioAuditRoute
  '/studio/media': typeof StudioMediaRoute
  '/founder/': typeof FounderIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/quests/': typeof QuestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/founder/collections/$id': typeof FounderCollectionsIdRoute
  '/founder/quests/$id': typeof FounderQuestsIdRoute
  '/founder/quests/new': typeof FounderQuestsNewRoute
  '/players/$username/compare': typeof PlayersUsernameCompareRoute
  '/quests/$slug/play': typeof QuestsSlugPlayRoute
  '/studio/players/$userId': typeof StudioPlayersUserIdRoute
  '/founder/quests/': typeof FounderQuestsIndexRoute
  '/studio/players/': typeof StudioPlayersIndexRoute
  '/api/public/hooks/liveops-tick': typeof ApiPublicHooksLiveopsTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRouteWithChildren
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/starter': typeof StarterRoute
  '/titles': typeof TitlesRoute
  '/tutorial': typeof TutorialRoute
  '/welcome': typeof WelcomeRoute
  '/xp-history': typeof XpHistoryRoute
  '/achievements/$slug': typeof AchievementsSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/founder/achievements': typeof FounderAchievementsRoute
  '/founder/collections': typeof FounderCollectionsRouteWithChildren
  '/founder/liveops': typeof FounderLiveopsRoute
  '/founder/social': typeof FounderSocialRoute
  '/founder/titles': typeof FounderTitlesRoute
  '/players/$username': typeof PlayersUsernameRouteWithChildren
  '/quests/$slug': typeof QuestsSlugRouteWithChildren
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/social': typeof SettingsSocialRoute
  '/studio/audit': typeof StudioAuditRoute
  '/studio/media': typeof StudioMediaRoute
  '/founder': typeof FounderIndexRoute
  '/players': typeof PlayersIndexRoute
  '/quests': typeof QuestsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/studio': typeof StudioIndexRoute
  '/founder/collections/$id': typeof FounderCollectionsIdRoute
  '/founder/quests/$id': typeof FounderQuestsIdRoute
  '/founder/quests/new': typeof FounderQuestsNewRoute
  '/players/$username/compare': typeof PlayersUsernameCompareRoute
  '/quests/$slug/play': typeof QuestsSlugPlayRoute
  '/studio/players/$userId': typeof StudioPlayersUserIdRoute
  '/founder/quests': typeof FounderQuestsIndexRoute
  '/studio/players': typeof StudioPlayersIndexRoute
  '/api/public/hooks/liveops-tick': typeof ApiPublicHooksLiveopsTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRouteWithChildren
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/founder': typeof FounderRouteWithChildren
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/starter': typeof StarterRoute
  '/studio': typeof StudioRouteWithChildren
  '/titles': typeof TitlesRoute
  '/tutorial': typeof TutorialRoute
  '/welcome': typeof WelcomeRoute
  '/xp-history': typeof XpHistoryRoute
  '/achievements/$slug': typeof AchievementsSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/founder/achievements': typeof FounderAchievementsRoute
  '/founder/collections': typeof FounderCollectionsRouteWithChildren
  '/founder/liveops': typeof FounderLiveopsRoute
  '/founder/social': typeof FounderSocialRoute
  '/founder/titles': typeof FounderTitlesRoute
  '/players/$username': typeof PlayersUsernameRouteWithChildren
  '/quests/$slug': typeof QuestsSlugRouteWithChildren
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/social': typeof SettingsSocialRoute
  '/studio/audit': typeof StudioAuditRoute
  '/studio/media': typeof StudioMediaRoute
  '/founder/': typeof FounderIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/quests/': typeof QuestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/founder/collections/$id': typeof FounderCollectionsIdRoute
  '/founder/quests/$id': typeof FounderQuestsIdRoute
  '/founder/quests/new': typeof FounderQuestsNewRoute
  '/players/$username/compare': typeof PlayersUsernameCompareRoute
  '/quests/$slug/play': typeof QuestsSlugPlayRoute
  '/studio/players/$userId': typeof StudioPlayersUserIdRoute
  '/founder/quests/': typeof FounderQuestsIndexRoute
  '/studio/players/': typeof StudioPlayersIndexRoute
  '/api/public/hooks/liveops-tick': typeof ApiPublicHooksLiveopsTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/activity'
    | '/auth'
    | '/challenges'
    | '/collections'
    | '/events'
    | '/founder'
    | '/home'
    | '/leaderboard'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/profile-setup'
    | '/rules'
    | '/sitemap.xml'
    | '/starter'
    | '/studio'
    | '/titles'
    | '/tutorial'
    | '/welcome'
    | '/xp-history'
    | '/achievements/$slug'
    | '/collections/$slug'
    | '/events/$slug'
    | '/founder/achievements'
    | '/founder/collections'
    | '/founder/liveops'
    | '/founder/social'
    | '/founder/titles'
    | '/players/$username'
    | '/quests/$slug'
    | '/settings/profile'
    | '/settings/social'
    | '/studio/audit'
    | '/studio/media'
    | '/founder/'
    | '/players/'
    | '/quests/'
    | '/settings/'
    | '/studio/'
    | '/founder/collections/$id'
    | '/founder/quests/$id'
    | '/founder/quests/new'
    | '/players/$username/compare'
    | '/quests/$slug/play'
    | '/studio/players/$userId'
    | '/founder/quests/'
    | '/studio/players/'
    | '/api/public/hooks/liveops-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/activity'
    | '/auth'
    | '/challenges'
    | '/collections'
    | '/events'
    | '/home'
    | '/leaderboard'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/profile-setup'
    | '/rules'
    | '/sitemap.xml'
    | '/starter'
    | '/titles'
    | '/tutorial'
    | '/welcome'
    | '/xp-history'
    | '/achievements/$slug'
    | '/collections/$slug'
    | '/events/$slug'
    | '/founder/achievements'
    | '/founder/collections'
    | '/founder/liveops'
    | '/founder/social'
    | '/founder/titles'
    | '/players/$username'
    | '/quests/$slug'
    | '/settings/profile'
    | '/settings/social'
    | '/studio/audit'
    | '/studio/media'
    | '/founder'
    | '/players'
    | '/quests'
    | '/settings'
    | '/studio'
    | '/founder/collections/$id'
    | '/founder/quests/$id'
    | '/founder/quests/new'
    | '/players/$username/compare'
    | '/quests/$slug/play'
    | '/studio/players/$userId'
    | '/founder/quests'
    | '/studio/players'
    | '/api/public/hooks/liveops-tick'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/activity'
    | '/auth'
    | '/challenges'
    | '/collections'
    | '/events'
    | '/founder'
    | '/home'
    | '/leaderboard'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/profile-setup'
    | '/rules'
    | '/sitemap.xml'
    | '/starter'
    | '/studio'
    | '/titles'
    | '/tutorial'
    | '/welcome'
    | '/xp-history'
    | '/achievements/$slug'
    | '/collections/$slug'
    | '/events/$slug'
    | '/founder/achievements'
    | '/founder/collections'
    | '/founder/liveops'
    | '/founder/social'
    | '/founder/titles'
    | '/players/$username'
    | '/quests/$slug'
    | '/settings/profile'
    | '/settings/social'
    | '/studio/audit'
    | '/studio/media'
    | '/founder/'
    | '/players/'
    | '/quests/'
    | '/settings/'
    | '/studio/'
    | '/founder/collections/$id'
    | '/founder/quests/$id'
    | '/founder/quests/new'
    | '/players/$username/compare'
    | '/quests/$slug/play'
    | '/studio/players/$userId'
    | '/founder/quests/'
    | '/studio/players/'
    | '/api/public/hooks/liveops-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRouteWithChildren
  ActivityRoute: typeof ActivityRoute
  AuthRoute: typeof AuthRoute
  ChallengesRoute: typeof ChallengesRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  FounderRoute: typeof FounderRouteWithChildren
  HomeRoute: typeof HomeRoute
  LeaderboardRoute: typeof LeaderboardRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  RulesRoute: typeof RulesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StarterRoute: typeof StarterRoute
  StudioRoute: typeof StudioRouteWithChildren
  TitlesRoute: typeof TitlesRoute
  TutorialRoute: typeof TutorialRoute
  WelcomeRoute: typeof WelcomeRoute
  XpHistoryRoute: typeof XpHistoryRoute
  PlayersUsernameRoute: typeof PlayersUsernameRouteWithChildren
  QuestsSlugRoute: typeof QuestsSlugRouteWithChildren
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSocialRoute: typeof SettingsSocialRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  QuestsIndexRoute: typeof QuestsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApiPublicHooksLiveopsTickRoute: typeof ApiPublicHooksLiveopsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xp-history': {
      id: '/xp-history'
      path: '/xp-history'
      fullPath: '/xp-history'
      preLoaderRoute: typeof XpHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/titles': {
      id: '/titles'
      path: '/titles'
      fullPath: '/titles'
      preLoaderRoute: typeof TitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starter': {
      id: '/starter'
      path: '/starter'
      fullPath: '/starter'
      preLoaderRoute: typeof StarterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/': {
      id: '/quests/'
      path: '/quests'
      fullPath: '/quests/'
      preLoaderRoute: typeof QuestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/': {
      id: '/founder/'
      path: '/'
      fullPath: '/founder/'
      preLoaderRoute: typeof FounderIndexRouteImport
      parentRoute: typeof FounderRoute
    }
    '/studio/media': {
      id: '/studio/media'
      path: '/media'
      fullPath: '/studio/media'
      preLoaderRoute: typeof StudioMediaRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/audit': {
      id: '/studio/audit'
      path: '/audit'
      fullPath: '/studio/audit'
      preLoaderRoute: typeof StudioAuditRouteImport
      parentRoute: typeof StudioRoute
    }
    '/settings/social': {
      id: '/settings/social'
      path: '/settings/social'
      fullPath: '/settings/social'
      preLoaderRoute: typeof SettingsSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/$slug': {
      id: '/quests/$slug'
      path: '/quests/$slug'
      fullPath: '/quests/$slug'
      preLoaderRoute: typeof QuestsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$username': {
      id: '/players/$username'
      path: '/players/$username'
      fullPath: '/players/$username'
      preLoaderRoute: typeof PlayersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/titles': {
      id: '/founder/titles'
      path: '/titles'
      fullPath: '/founder/titles'
      preLoaderRoute: typeof FounderTitlesRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/social': {
      id: '/founder/social'
      path: '/social'
      fullPath: '/founder/social'
      preLoaderRoute: typeof FounderSocialRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/liveops': {
      id: '/founder/liveops'
      path: '/liveops'
      fullPath: '/founder/liveops'
      preLoaderRoute: typeof FounderLiveopsRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/collections': {
      id: '/founder/collections'
      path: '/collections'
      fullPath: '/founder/collections'
      preLoaderRoute: typeof FounderCollectionsRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/achievements': {
      id: '/founder/achievements'
      path: '/achievements'
      fullPath: '/founder/achievements'
      preLoaderRoute: typeof FounderAchievementsRouteImport
      parentRoute: typeof FounderRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/achievements/$slug': {
      id: '/achievements/$slug'
      path: '/$slug'
      fullPath: '/achievements/$slug'
      preLoaderRoute: typeof AchievementsSlugRouteImport
      parentRoute: typeof AchievementsRoute
    }
    '/studio/players/': {
      id: '/studio/players/'
      path: '/players'
      fullPath: '/studio/players/'
      preLoaderRoute: typeof StudioPlayersIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/founder/quests/': {
      id: '/founder/quests/'
      path: '/quests'
      fullPath: '/founder/quests/'
      preLoaderRoute: typeof FounderQuestsIndexRouteImport
      parentRoute: typeof FounderRoute
    }
    '/studio/players/$userId': {
      id: '/studio/players/$userId'
      path: '/players/$userId'
      fullPath: '/studio/players/$userId'
      preLoaderRoute: typeof StudioPlayersUserIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/quests/$slug/play': {
      id: '/quests/$slug/play'
      path: '/play'
      fullPath: '/quests/$slug/play'
      preLoaderRoute: typeof QuestsSlugPlayRouteImport
      parentRoute: typeof QuestsSlugRoute
    }
    '/players/$username/compare': {
      id: '/players/$username/compare'
      path: '/compare'
      fullPath: '/players/$username/compare'
      preLoaderRoute: typeof PlayersUsernameCompareRouteImport
      parentRoute: typeof PlayersUsernameRoute
    }
    '/founder/quests/new': {
      id: '/founder/quests/new'
      path: '/quests/new'
      fullPath: '/founder/quests/new'
      preLoaderRoute: typeof FounderQuestsNewRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/quests/$id': {
      id: '/founder/quests/$id'
      path: '/quests/$id'
      fullPath: '/founder/quests/$id'
      preLoaderRoute: typeof FounderQuestsIdRouteImport
      parentRoute: typeof FounderRoute
    }
    '/founder/collections/$id': {
      id: '/founder/collections/$id'
      path: '/$id'
      fullPath: '/founder/collections/$id'
      preLoaderRoute: typeof FounderCollectionsIdRouteImport
      parentRoute: typeof FounderCollectionsRoute
    }
    '/api/public/hooks/liveops-tick': {
      id: '/api/public/hooks/liveops-tick'
      path: '/api/public/hooks/liveops-tick'
      fullPath: '/api/public/hooks/liveops-tick'
      preLoaderRoute: typeof ApiPublicHooksLiveopsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AchievementsRouteChildren {
  AchievementsSlugRoute: typeof AchievementsSlugRoute
}

const AchievementsRouteChildren: AchievementsRouteChildren = {
  AchievementsSlugRoute: AchievementsSlugRoute,
}

const AchievementsRouteWithChildren = AchievementsRoute._addFileChildren(
  AchievementsRouteChildren,
)

interface CollectionsRouteChildren {
  CollectionsSlugRoute: typeof CollectionsSlugRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsSlugRoute: CollectionsSlugRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface FounderCollectionsRouteChildren {
  FounderCollectionsIdRoute: typeof FounderCollectionsIdRoute
}

const FounderCollectionsRouteChildren: FounderCollectionsRouteChildren = {
  FounderCollectionsIdRoute: FounderCollectionsIdRoute,
}

const FounderCollectionsRouteWithChildren =
  FounderCollectionsRoute._addFileChildren(FounderCollectionsRouteChildren)

interface FounderRouteChildren {
  FounderAchievementsRoute: typeof FounderAchievementsRoute
  FounderCollectionsRoute: typeof FounderCollectionsRouteWithChildren
  FounderLiveopsRoute: typeof FounderLiveopsRoute
  FounderSocialRoute: typeof FounderSocialRoute
  FounderTitlesRoute: typeof FounderTitlesRoute
  FounderIndexRoute: typeof FounderIndexRoute
  FounderQuestsIdRoute: typeof FounderQuestsIdRoute
  FounderQuestsNewRoute: typeof FounderQuestsNewRoute
  FounderQuestsIndexRoute: typeof FounderQuestsIndexRoute
}

const FounderRouteChildren: FounderRouteChildren = {
  FounderAchievementsRoute: FounderAchievementsRoute,
  FounderCollectionsRoute: FounderCollectionsRouteWithChildren,
  FounderLiveopsRoute: FounderLiveopsRoute,
  FounderSocialRoute: FounderSocialRoute,
  FounderTitlesRoute: FounderTitlesRoute,
  FounderIndexRoute: FounderIndexRoute,
  FounderQuestsIdRoute: FounderQuestsIdRoute,
  FounderQuestsNewRoute: FounderQuestsNewRoute,
  FounderQuestsIndexRoute: FounderQuestsIndexRoute,
}

const FounderRouteWithChildren =
  FounderRoute._addFileChildren(FounderRouteChildren)

interface StudioRouteChildren {
  StudioAuditRoute: typeof StudioAuditRoute
  StudioMediaRoute: typeof StudioMediaRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioPlayersUserIdRoute: typeof StudioPlayersUserIdRoute
  StudioPlayersIndexRoute: typeof StudioPlayersIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAuditRoute: StudioAuditRoute,
  StudioMediaRoute: StudioMediaRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioPlayersUserIdRoute: StudioPlayersUserIdRoute,
  StudioPlayersIndexRoute: StudioPlayersIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

interface PlayersUsernameRouteChildren {
  PlayersUsernameCompareRoute: typeof PlayersUsernameCompareRoute
}

const PlayersUsernameRouteChildren: PlayersUsernameRouteChildren = {
  PlayersUsernameCompareRoute: PlayersUsernameCompareRoute,
}

const PlayersUsernameRouteWithChildren = PlayersUsernameRoute._addFileChildren(
  PlayersUsernameRouteChildren,
)

interface QuestsSlugRouteChildren {
  QuestsSlugPlayRoute: typeof QuestsSlugPlayRoute
}

const QuestsSlugRouteChildren: QuestsSlugRouteChildren = {
  QuestsSlugPlayRoute: QuestsSlugPlayRoute,
}

const QuestsSlugRouteWithChildren = QuestsSlugRoute._addFileChildren(
  QuestsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRouteWithChildren,
  ActivityRoute: ActivityRoute,
  AuthRoute: AuthRoute,
  ChallengesRoute: ChallengesRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  FounderRoute: FounderRouteWithChildren,
  HomeRoute: HomeRoute,
  LeaderboardRoute: LeaderboardRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  RulesRoute: RulesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StarterRoute: StarterRoute,
  StudioRoute: StudioRouteWithChildren,
  TitlesRoute: TitlesRoute,
  TutorialRoute: TutorialRoute,
  WelcomeRoute: WelcomeRoute,
  XpHistoryRoute: XpHistoryRoute,
  PlayersUsernameRoute: PlayersUsernameRouteWithChildren,
  QuestsSlugRoute: QuestsSlugRouteWithChildren,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSocialRoute: SettingsSocialRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  QuestsIndexRoute: QuestsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ApiPublicHooksLiveopsTickRoute: ApiPublicHooksLiveopsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
