/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XpHistoryRouteImport } from './routes/xp-history'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as TitlesRouteImport } from './routes/titles'
import { Route as StarterRouteImport } from './routes/starter'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestsIndexRouteImport } from './routes/quests.index'
import { Route as FounderIndexRouteImport } from './routes/founder.index'
import { Route as QuestsSlugRouteImport } from './routes/quests.$slug'
import { Route as FounderTitlesRouteImport } from './routes/founder.titles'
import { Route as FounderAchievementsRouteImport } from './routes/founder.achievements'
import { Route as AchievementsSlugRouteImport } from './routes/achievements.$slug'
import { Route as FounderQuestsIndexRouteImport } from './routes/founder.quests.index'
import { Route as QuestsSlugPlayRouteImport } from './routes/quests.$slug.play'
import { Route as FounderQuestsNewRouteImport } from './routes/founder.quests.new'
import { Route as FounderQuestsIdRouteImport } from './routes/founder.quests.$id'

const XpHistoryRoute = XpHistoryRouteImport.update({
  id: '/xp-history',
  path: '/xp-history',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const TitlesRoute = TitlesRouteImport.update({
  id: '/titles',
  path: '/titles',
  getParentRoute: () => rootRouteImport,
} as any)
const StarterRoute = StarterRouteImport.update({
  id: '/starter',
  path: '/starter',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsIndexRoute = QuestsIndexRouteImport.update({
  id: '/quests/',
  path: '/quests/',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderIndexRoute = FounderIndexRouteImport.update({
  id: '/founder/',
  path: '/founder/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsSlugRoute = QuestsSlugRouteImport.update({
  id: '/quests/$slug',
  path: '/quests/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderTitlesRoute = FounderTitlesRouteImport.update({
  id: '/founder/titles',
  path: '/founder/titles',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderAchievementsRoute = FounderAchievementsRouteImport.update({
  id: '/founder/achievements',
  path: '/founder/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsSlugRoute = AchievementsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AchievementsRoute,
} as any)
const FounderQuestsIndexRoute = FounderQuestsIndexRouteImport.update({
  id: '/founder/quests/',
  path: '/founder/quests/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsSlugPlayRoute = QuestsSlugPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => QuestsSlugRoute,
} as any)
const FounderQuestsNewRoute = FounderQuestsNewRouteImport.update({
  id: '/founder/quests/new',
  path: '/founder/quests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderQuestsIdRoute = FounderQuestsIdRouteImport.update({
  id: '/founder/quests/$id',
  path: '/founder/quests/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRouteWithChildren
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/starter': typeof StarterRoute
  '/titles': typeof TitlesRoute
  '/tutorial': typeof TutorialRoute
  '/welcome': typeof WelcomeRoute
  '/xp-history': typeof XpHistoryRoute
  '/achievements/$slug': typeof AchievementsSlugRoute
  '/founder/achievements': typeof FounderAchievementsRoute
  '/founder/titles': typeof FounderTitlesRoute
  '/quests/$slug': typeof QuestsSlugRouteWithChildren
  '/founder/': typeof FounderIndexRoute
  '/quests/': typeof QuestsIndexRoute
  '/founder/quests/$id': typeof FounderQuestsIdRoute
  '/founder/quests/new': typeof FounderQuestsNewRoute
  '/quests/$slug/play': typeof QuestsSlugPlayRoute
  '/founder/quests/': typeof FounderQuestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRouteWithChildren
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/starter': typeof StarterRoute
  '/titles': typeof TitlesRoute
  '/tutorial': typeof TutorialRoute
  '/welcome': typeof WelcomeRoute
  '/xp-history': typeof XpHistoryRoute
  '/achievements/$slug': typeof AchievementsSlugRoute
  '/founder/achievements': typeof FounderAchievementsRoute
  '/founder/titles': typeof FounderTitlesRoute
  '/quests/$slug': typeof QuestsSlugRouteWithChildren
  '/founder': typeof FounderIndexRoute
  '/quests': typeof QuestsIndexRoute
  '/founder/quests/$id': typeof FounderQuestsIdRoute
  '/founder/quests/new': typeof FounderQuestsNewRoute
  '/quests/$slug/play': typeof QuestsSlugPlayRoute
  '/founder/quests': typeof FounderQuestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRouteWithChildren
  '/auth': typeof AuthRoute
  '/collections': typeof CollectionsRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/rules': typeof RulesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/starter': typeof StarterRoute
  '/titles': typeof TitlesRoute
  '/tutorial': typeof TutorialRoute
  '/welcome': typeof WelcomeRoute
  '/xp-history': typeof XpHistoryRoute
  '/achievements/$slug': typeof AchievementsSlugRoute
  '/founder/achievements': typeof FounderAchievementsRoute
  '/founder/titles': typeof FounderTitlesRoute
  '/quests/$slug': typeof QuestsSlugRouteWithChildren
  '/founder/': typeof FounderIndexRoute
  '/quests/': typeof QuestsIndexRoute
  '/founder/quests/$id': typeof FounderQuestsIdRoute
  '/founder/quests/new': typeof FounderQuestsNewRoute
  '/quests/$slug/play': typeof QuestsSlugPlayRoute
  '/founder/quests/': typeof FounderQuestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/auth'
    | '/collections'
    | '/home'
    | '/leaderboard'
    | '/onboarding'
    | '/profile'
    | '/profile-setup'
    | '/rules'
    | '/settings'
    | '/sitemap.xml'
    | '/starter'
    | '/titles'
    | '/tutorial'
    | '/welcome'
    | '/xp-history'
    | '/achievements/$slug'
    | '/founder/achievements'
    | '/founder/titles'
    | '/quests/$slug'
    | '/founder/'
    | '/quests/'
    | '/founder/quests/$id'
    | '/founder/quests/new'
    | '/quests/$slug/play'
    | '/founder/quests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/auth'
    | '/collections'
    | '/home'
    | '/leaderboard'
    | '/onboarding'
    | '/profile'
    | '/profile-setup'
    | '/rules'
    | '/settings'
    | '/sitemap.xml'
    | '/starter'
    | '/titles'
    | '/tutorial'
    | '/welcome'
    | '/xp-history'
    | '/achievements/$slug'
    | '/founder/achievements'
    | '/founder/titles'
    | '/quests/$slug'
    | '/founder'
    | '/quests'
    | '/founder/quests/$id'
    | '/founder/quests/new'
    | '/quests/$slug/play'
    | '/founder/quests'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/auth'
    | '/collections'
    | '/home'
    | '/leaderboard'
    | '/onboarding'
    | '/profile'
    | '/profile-setup'
    | '/rules'
    | '/settings'
    | '/sitemap.xml'
    | '/starter'
    | '/titles'
    | '/tutorial'
    | '/welcome'
    | '/xp-history'
    | '/achievements/$slug'
    | '/founder/achievements'
    | '/founder/titles'
    | '/quests/$slug'
    | '/founder/'
    | '/quests/'
    | '/founder/quests/$id'
    | '/founder/quests/new'
    | '/quests/$slug/play'
    | '/founder/quests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRouteWithChildren
  AuthRoute: typeof AuthRoute
  CollectionsRoute: typeof CollectionsRoute
  HomeRoute: typeof HomeRoute
  LeaderboardRoute: typeof LeaderboardRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  RulesRoute: typeof RulesRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StarterRoute: typeof StarterRoute
  TitlesRoute: typeof TitlesRoute
  TutorialRoute: typeof TutorialRoute
  WelcomeRoute: typeof WelcomeRoute
  XpHistoryRoute: typeof XpHistoryRoute
  FounderAchievementsRoute: typeof FounderAchievementsRoute
  FounderTitlesRoute: typeof FounderTitlesRoute
  QuestsSlugRoute: typeof QuestsSlugRouteWithChildren
  FounderIndexRoute: typeof FounderIndexRoute
  QuestsIndexRoute: typeof QuestsIndexRoute
  FounderQuestsIdRoute: typeof FounderQuestsIdRoute
  FounderQuestsNewRoute: typeof FounderQuestsNewRoute
  FounderQuestsIndexRoute: typeof FounderQuestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xp-history': {
      id: '/xp-history'
      path: '/xp-history'
      fullPath: '/xp-history'
      preLoaderRoute: typeof XpHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/titles': {
      id: '/titles'
      path: '/titles'
      fullPath: '/titles'
      preLoaderRoute: typeof TitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starter': {
      id: '/starter'
      path: '/starter'
      fullPath: '/starter'
      preLoaderRoute: typeof StarterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/': {
      id: '/quests/'
      path: '/quests'
      fullPath: '/quests/'
      preLoaderRoute: typeof QuestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/': {
      id: '/founder/'
      path: '/founder'
      fullPath: '/founder/'
      preLoaderRoute: typeof FounderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/$slug': {
      id: '/quests/$slug'
      path: '/quests/$slug'
      fullPath: '/quests/$slug'
      preLoaderRoute: typeof QuestsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/titles': {
      id: '/founder/titles'
      path: '/founder/titles'
      fullPath: '/founder/titles'
      preLoaderRoute: typeof FounderTitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/achievements': {
      id: '/founder/achievements'
      path: '/founder/achievements'
      fullPath: '/founder/achievements'
      preLoaderRoute: typeof FounderAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements/$slug': {
      id: '/achievements/$slug'
      path: '/$slug'
      fullPath: '/achievements/$slug'
      preLoaderRoute: typeof AchievementsSlugRouteImport
      parentRoute: typeof AchievementsRoute
    }
    '/founder/quests/': {
      id: '/founder/quests/'
      path: '/founder/quests'
      fullPath: '/founder/quests/'
      preLoaderRoute: typeof FounderQuestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/$slug/play': {
      id: '/quests/$slug/play'
      path: '/play'
      fullPath: '/quests/$slug/play'
      preLoaderRoute: typeof QuestsSlugPlayRouteImport
      parentRoute: typeof QuestsSlugRoute
    }
    '/founder/quests/new': {
      id: '/founder/quests/new'
      path: '/founder/quests/new'
      fullPath: '/founder/quests/new'
      preLoaderRoute: typeof FounderQuestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder/quests/$id': {
      id: '/founder/quests/$id'
      path: '/founder/quests/$id'
      fullPath: '/founder/quests/$id'
      preLoaderRoute: typeof FounderQuestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AchievementsRouteChildren {
  AchievementsSlugRoute: typeof AchievementsSlugRoute
}

const AchievementsRouteChildren: AchievementsRouteChildren = {
  AchievementsSlugRoute: AchievementsSlugRoute,
}

const AchievementsRouteWithChildren = AchievementsRoute._addFileChildren(
  AchievementsRouteChildren,
)

interface QuestsSlugRouteChildren {
  QuestsSlugPlayRoute: typeof QuestsSlugPlayRoute
}

const QuestsSlugRouteChildren: QuestsSlugRouteChildren = {
  QuestsSlugPlayRoute: QuestsSlugPlayRoute,
}

const QuestsSlugRouteWithChildren = QuestsSlugRoute._addFileChildren(
  QuestsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRouteWithChildren,
  AuthRoute: AuthRoute,
  CollectionsRoute: CollectionsRoute,
  HomeRoute: HomeRoute,
  LeaderboardRoute: LeaderboardRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  RulesRoute: RulesRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StarterRoute: StarterRoute,
  TitlesRoute: TitlesRoute,
  TutorialRoute: TutorialRoute,
  WelcomeRoute: WelcomeRoute,
  XpHistoryRoute: XpHistoryRoute,
  FounderAchievementsRoute: FounderAchievementsRoute,
  FounderTitlesRoute: FounderTitlesRoute,
  QuestsSlugRoute: QuestsSlugRouteWithChildren,
  FounderIndexRoute: FounderIndexRoute,
  QuestsIndexRoute: QuestsIndexRoute,
  FounderQuestsIdRoute: FounderQuestsIdRoute,
  FounderQuestsNewRoute: FounderQuestsNewRoute,
  FounderQuestsIndexRoute: FounderQuestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
